php artisan make:migration create_scholar_years_table;
sleep 1;
php artisan make:migration create_grade_levels_table;
sleep 1;
php artisan make:migration create_formations_table;
sleep 1;
php artisan make:migration create_class_groups_table;
sleep 1;
php artisan make:migration create_users_table;
sleep 1;
php artisan make:migration create_class_teachers_table;
sleep 1;
php artisan make:migration create_skills_table;
sleep 1;
php artisan make:migration create_levels_table;
sleep 1;
php artisan make:migration create_skill_levels_table;
sleep 1;
php artisan make:migration create_sprints_table;
sleep 1;
php artisan make:migration create_sprint_skills_table;
sleep 1;
php artisan make:migration create_squads_table;
sleep 1;
php artisan make:migration create_squad_members_table;
sleep 1;
php artisan make:migration create_briefs_table;
sleep 1;
php artisan make:migration create_brief_skill_levels_table;
sleep 1;
php artisan make:migration create_submissions_table;
sleep 1;
php artisan make:migration create_corrections_table;
sleep 1;
php artisan make:migration create_correction_details_table;
sleep 1;
